<a href="https://colab.research.google.com/github/saivigneshmuthyam1/numpy_/blob/main/TekWorks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello")

Hello


In [ ]:
pip show numpy

Name: numpy
Version: 2.0.2
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: Copyright (c) 2005-2024, NumPy Developers.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

    * Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.

    * Redistributions in binary form must reproduce the above
       copyright notice, this list of conditions and the following
       disclaimer in the documentation and/or other materials provided
       with the distribution.

    * Neither the name of the NumPy Developers nor the names of any
       contributors may be used to endorse or promote products derived
       from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRI

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
arr=[0]
print(arr)
arr.append(10)
print(arr)
x=arr
print(x)
x=[0]
print(x)
print(arr)


[1 2 3 4 5]
[0]
[0, 10]
[0, 10]
[0]
[0, 10]


In [ ]:
arr_2d = np.array([[[1, 2, 3], [4, 5, 6],[7,8,9]],[[2,3,4],[5,6,7],[8,9,10]]] )
print(arr_2d)
print(arr_2d.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 2  3  4]
  [ 5  6  7]
  [ 8  9 10]]]
3


In [ ]:
arr=np.zeros((2,3))
print(arr)
print(arr.ndim)
arr_1=np.random.random((2,3))
print(arr_1)

[[0. 0. 0.]
 [0. 0. 0.]]
2
[[0.75879233 0.94042946 0.73003643]
 [0.26420692 0.98670758 0.43165938]]


In [ ]:
arr=np.arange(0,10,2)
print(arr)
arr_1=np.linspace(0,10,5)
print(arr_1)

[0 2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]


In [ ]:
arr=np.zeros((2,3))
print(arr)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)
6
float64
2


In [ ]:
import numpy as np

# Temperature data for two greenhouses
gh1_temp = [25, 26, 24]
gh2_temp = [22, 24, 23]

# Create a 2D NumPy array
temp_data = np.array([gh1_temp, gh2_temp])

# Print the array
print("Temperature Data (2 Greenhouses):")
print(temp_data)
print("-" * 20)

# Check array properties
print("Shape:", temp_data.shape)
print("Size:", temp_data.size)
print("Data type:", temp_data.dtype)
print("Number of dimensions:", temp_data.ndim)
print("-" * 20)

# Add a third greenhouse
gh3_temp = [21, 23, 22]
updated_temp_data = np.vstack([temp_data, gh3_temp])

# Generate supporting data
sensor_error_flags = np.zeros((2, 3))
greenhouse_identity = np.identity(3)

# Display all arrays
print("Updated Temperature Data (3 Greenhouses):")
print(updated_temp_data)
print("-" * 20)
print("Sensor Error Flags:")
print(sensor_error_flags)
print("-" * 20)
print("Greenhouse Identity Matrix:")
print(greenhouse_identity)

Temperature Data (2 Greenhouses):
[[25 26 24]
 [22 24 23]]
--------------------
Shape: (2, 3)
Size: 6
Data type: int64
Number of dimensions: 2
--------------------
Updated Temperature Data (3 Greenhouses):
[[25 26 24]
 [22 24 23]
 [21 23 22]]
--------------------
Sensor Error Flags:
[[0. 0. 0.]
 [0. 0. 0.]]
--------------------
Greenhouse Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Indexing and Slicing:
You are working as a Data Analyst at a fruit distribution company.

The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:
Each row represents a type of fruit.
Each column represents a day of the week (Mon–Sun).


Your Tasks
Create the 2D NumPy array

Create an array named shipments using the above data.
Access single elements (Indexing):
Get the number of Apples shipped on Wednesday.
Get the number of Oranges shipped on Sunday.
Access multiple elements (Slicing):
Extract all the weekday shipments (Mon–Fri) for all fruits.
Extract only the weekend shipments (Sat & Sun).
Extract the shipments of Apples from Wednesday to Saturday.
Bonus (Practice thinking):
Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.


In [ ]:
import numpy as np

# Data: Number of fruit boxes shipped per day for 1 week
# Rows: Fruit types (Apples, Oranges, Bananas)
# Columns: Days of the week (Mon-Sun)
data = [
    [100, 120, 110, 130, 150, 80, 90],  # Apples
    [80, 90, 85, 95, 100, 70, 75],      # Oranges
    [110, 100, 105, 115, 120, 90, 85]   # Bananas
]

# Create the 2D NumPy array
shipments = np.array(data)

print("Shipments Array:")
print(shipments)
print("-" * 30)

# Access single elements (Indexing):
# Get the number of Apples shipped on Wednesday (Apples are row 0, Wednesday is column 2)
apples_wednesday = shipments[0, 2]
print(f"Apples shipped on Wednesday: {apples_wednesday}")

# Get the number of Oranges shipped on Sunday (Oranges are row 1, Sunday is column 6)
oranges_sunday = shipments[1, 6]
print(f"Oranges shipped on Sunday: {oranges_sunday}")
print("-" * 30)

# Access multiple elements (Slicing):
# Extract all the weekday shipments (Mon-Fri) for all fruits (all rows, columns 0 to 4)
weekday_shipments = shipments[:, 0:5]
print("Weekday Shipments:")
print(weekday_shipments)

# Extract only the weekend shipments (Sat & Sun) (all rows, columns 5 and 6)
weekend_shipments = shipments[:, 5:7]
print("\nWeekend Shipments:")
print(weekend_shipments)

# Extract the shipments of Apples from Wednesday to Saturday (Apples are row 0, columns 2 to 5)
apples_wed_to_sat = shipments[0, 2:6]
print(f"\nApples shipments from Wednesday to Saturday: {apples_wed_to_sat}")
print("-" * 30)

# Bonus (Practice thinking):
# Replace the Saturday shipment of Apples (currently 80) with 100 using indexing
# Saturday shipment of Apples is at row 0, column 5
shipments[0, 5] = 100
print("Updated Shipments Array (Saturday Apples replaced):")
print(shipments)

Shipments Array:
[[100 120 110 130 150  80  90]
 [ 80  90  85  95 100  70  75]
 [110 100 105 115 120  90  85]]
------------------------------
Apples shipped on Wednesday: 110
Oranges shipped on Sunday: 75
------------------------------
Weekday Shipments:
[[100 120 110 130 150]
 [ 80  90  85  95 100]
 [110 100 105 115 120]]

Weekend Shipments:
[[80 90]
 [70 75]
 [90 85]]

Apples shipments from Wednesday to Saturday: [110 130 150  80]
------------------------------
Updated Shipments Array (Saturday Apples replaced):
[[100 120 110 130 150 100  90]
 [ 80  90  85  95 100  70  75]
 [110 100 105 115 120  90  85]]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a*b)
print(a*2)
print(a,b)
print(a.shape,b.shape)
print(np.dot(a,b))
print(a+2)

[5 7 9]
[ 4 10 18]
[2 4 6]
[1 2 3] [4 5 6]
(3,) (3,)
32
[3 4 5]


1. Arithmetic ufuncs
Operate element-wise on arrays.
np.add(x, y)
np.subtract(x, y)
np.multiply(x, y)
np.divide(x, y)
np.power(x, y)
np.mod(x, y)
🔹 2. Exponential and Logarithmic ufuncs
(You already covered these)
np.exp(x)
np.log(x)
np.log10(x)
np.log2(x)
np.expm1(x)    # exp(x) - 1
🔹 3. Trigonometric ufuncs
np.sin(x)
np.cos(x)
np.tan(x)
np.arcsin(x)
np.arccos(x)
np.arctan(x)
np.degrees(x)
np.radians(x)
🔹 4. Rounding ufuncs
np.round(x)
np.floor(x)
np.ceil(x)
np.trunc(x)
🔹 5. Statistical ufuncs
(Operate along an axis or entire array)
np.min(x)
np.max(x)
np.mean(x)
np.std(x)
np.var(x)
np.sum(x)
np.prod(x)
🔹 6. Logical ufuncs
np.logical_and(x, y)
np.logical_or(x, y)
np.logical_not(x)
np.logical_xor(x, y)
🔹 7. Comparison ufuncs
(Return Boolean arrays)
np.greater(x, y)
np.less(x, y)
np.equal(x, y)
np.not_equal(x, y)
np.greater_equal(x, y)
np.less_equal(x, y)
🔹 8. Bitwise ufuncs
(Operate on integers)
np.bitwise_and(x, y)
np.bitwise_or(x, y)
np.bitwise_xor(x, y)
np.invert(x)

In [ ]:
import numpy as np

# Create some example arrays
x = np.array([1, 2, 3, 4, 5])
y = np.array([5, 4, 3, 2, 1])
z = np.array([-1.5, 0.5, 1.5, 2.5, -2.5])
bool_arr1 = np.array([True, False, True, False, True])
bool_arr2 = np.array([False, True, True, False, False])

print("Example Arrays:")
print("x:", x)
print("y:", y)
print("z:", z)
print("bool_arr1:", bool_arr1)
print("bool_arr2:", bool_arr2)
print("-" * 30)

# 1. Arithmetic ufuncs
print("Arithmetic ufuncs:")
print("np.add(x, y):", np.add(x, y))
print("np.subtract(x, y):", np.subtract(x, y))
print("np.multiply(x, y):", np.multiply(x, y))
print("np.divide(x, y):", np.divide(x, y))
print("np.power(x, y):", np.power(x, y))
print("np.mod(y, x):", np.mod(y, x)) # Using y % x for demonstration
print("-" * 30)

# 2. Exponential and Logarithmic ufuncs
print("Exponential and Logarithmic ufuncs:")
print("np.exp(x):", np.exp(x))
print("np.log(x):", np.log(x)) # Natural logarithm
print("np.log10(x):", np.log10(x)) # Base 10 logarithm
print("np.log2(x):", np.log2(x)) # Base 2 logarithm
print("np.expm1(x):", np.expm1(x)) # exp(x) - 1
print("-" * 30)


# 3. Trigonometric ufuncs
print("Trigonometric ufuncs:")
# Convert degrees to radians for trigonometric functions
x_radians = np.radians(np.array([0, 30, 45, 60, 90]))
print("np.sin(x_radians):", np.sin(x_radians))
print("np.cos(x_radians):", np.cos(x_radians))
print("np.tan(x_radians):", np.tan(x_radians))
print("np.arcsin(np.sin(x_radians)):", np.arcsin(np.sin(x_radians))) # Inverse sin
print("np.arccos(np.cos(x_radians)):", np.arccos(np.cos(x_radians))) # Inverse cos
print("np.arctan(np.tan(x_radians)):", np.arctan(np.tan(x_radians))) # Inverse tan
print("np.degrees(x_radians):", np.degrees(x_radians)) # Convert radians back to degrees
print("-" * 30)

# 4. Rounding ufuncs
print("Rounding ufuncs:")
print("np.round(z):", np.round(z))
print("np.floor(z):", np.floor(z))
print("np.ceil(z):", np.ceil(z))
print("np.trunc(z):", np.trunc(z))
print("-" * 30)

# 5. Statistical ufuncs
print("Statistical ufuncs:")
print("np.min(x):", np.min(x))
print("np.max(x):", np.max(x))
print("np.mean(x):", np.mean(x))
print("np.std(x):", np.std(x))
print("np.var(x):", np.var(x))
print("np.sum(x):", np.sum(x))
print("np.prod(x):", np.prod(x))
print("-" * 30)

# 6. Logical ufuncs
print("Logical ufuncs:")
print("np.logical_and(bool_arr1, bool_arr2):", np.logical_and(bool_arr1, bool_arr2))
print("np.logical_or(bool_arr1, bool_arr2):", np.logical_or(bool_arr1, bool_arr2))
print("np.logical_not(bool_arr1):", np.logical_not(bool_arr1))
print("np.logical_xor(bool_arr1, bool_arr2):", np.logical_xor(bool_arr1, bool_arr2))
print("-" * 30)

# 7. Comparison ufuncs
print("Comparison ufuncs:")
print("np.greater(x, y):", np.greater(x, y))
print("np.less(x, y):", np.less(x, y))
print("np.equal(x, y):", np.equal(x, y))
print("np.not_equal(x, y):", np.not_equal(x, y))
print("np.greater_equal(x, y):", np.greater_equal(x, y))
print("np.less_equal(x, y):", np.less_equal(x, y))
print("-" * 30)

# 8. Bitwise ufuncs
# Using integer arrays for bitwise operations
int_x = np.array([10, 20, 30]) # Binary: 1010, 10100, 11110
int_y = np.array([3, 15, 25])  # Binary: 0011, 01111, 11001
print("Bitwise ufuncs (on integers):")
print("int_x:", int_x)
print("int_y:", int_y)
print("np.bitwise_and(int_x, int_y):", np.bitwise_and(int_x, int_y))
print("np.bitwise_or(int_x, int_y):", np.bitwise_or(int_x, int_y))
print("np.bitwise_xor(int_x, int_y):", np.bitwise_xor(int_x, int_y))
print("np.invert(int_x):", np.invert(int_x))

Example Arrays:
x: [1 2 3 4 5]
y: [5 4 3 2 1]
z: [-1.5  0.5  1.5  2.5 -2.5]
bool_arr1: [ True False  True False  True]
bool_arr2: [False  True  True False False]
------------------------------
Arithmetic ufuncs:
np.add(x, y): [6 6 6 6 6]
np.subtract(x, y): [-4 -2  0  2  4]
np.multiply(x, y): [5 8 9 8 5]
np.divide(x, y): [0.2 0.5 1.  2.  5. ]
np.power(x, y): [ 1 16 27 16  5]
np.mod(y, x): [0 0 0 2 1]
------------------------------
Exponential and Logarithmic ufuncs:
np.exp(x): [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
np.log(x): [0.         0.69314718 1.09861229 1.38629436 1.60943791]
np.log10(x): [0.         0.30103    0.47712125 0.60205999 0.69897   ]
np.log2(x): [0.         1.         1.5849625  2.         2.32192809]
np.expm1(x): [  1.71828183   6.3890561   19.08553692  53.59815003 147.4131591 ]
------------------------------
Trigonometric ufuncs:
np.sin(x_radians): [0.         0.5        0.70710678 0.8660254  1.        ]
np.cos(x_radians): [1.00000000e+00 8

You are a data engineer at a renewable-energy company that runs 3 solar farms.

Each farm has 4 solar panels, and each panel reports hourly energy production (kWh) for 3 hours during a test window.

Given data (raw)
Create arrays from these values:
production — shape (3 farms × 4 panels × 3 hours) represented as a 2D array per farm (you can stack/create as shown in tasks).
Farm A panels (rows = panels, cols = hours):


Tasks
Create arrays
Create three 2D NumPy arrays farmA, farmB, farmC (each shape (4,3)).
Stack them into a single 3D array production_all of shape (3, 4, 3).
Array attributes
Print the .shape, .size, .dtype, and .ndim of production_all.
Per-farm totals (arithmetic & aggregation)
Use aggregation ufuncs to compute the total energy per farm (sum across panels & hours) → total_per_farm (shape (3,)).
Compute mean, std, and var per farm.
Per-hour matrix multiplication idea (matrix op)
For a quick weighted estimate, create a hour_weights row vector of shape (3,) = [0.5, 1.0, 0.75] (weights for hour1, hour2, hour3).
Compute weighted_per_panel by performing a dot product between each farm's panel-row and hour_weights to get per-panel weighted energy. (Use np.dot / matrix multiplication appropriately.)
Broadcasting adjustments
The operator notices a fixed calibration offset of +0.5 kWh for all panels in Farm B. Use broadcasting to add this offset to Farm B data inside production_all (without recreating whole array manually).
Element-wise arithmetic (ufuncs: add/sub/mul/div/power/mod)
Compute a normalized version where you:
subtract the per-farm mean (use broadcasting),
divide by the per-farm std (broadcasting) — i.e., z-score normalize each farm's panel-hour readings.
Apply many ufuncs (use the ufuncs listed previously)

Apply the following element-wise operations (create variables for each) on the normalized data (or a copy) and show the resulting arrays (or summaries — shape/dtype/first row) where appropriate:
Exponential family: np.exp, np.expm1, np.log (note: handle non-positive inputs if needed), np.log10, np.log2.
Trigonometric: np.sin, np.cos, np.tan, np.arcsin, np.arccos, np.arctan, plus np.degrees, np.radians applied appropriately.
Rounding: np.round, np.floor, np.ceil, np.trunc.
Comparison & logical ufuncs: create a boolean mask high_output = production_all > 20 and apply np.logical_and, np.logical_or, np.logical_not, np.logical_xor combining masks (e.g., high_output and even_hours_mask). Also use comparison ufuncs like np.greater_equal, np.less.
Bitwise ufuncs (on integer arrays): create an integer array alerts = np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]]) for each farm (shape match required) — then apply np.bitwise_and, np.bitwise_or, np.invert where sensible.
Arithmetic ufuncs again: np.add, np.subtract, np.multiply, np.divide, np.power, np.mod.
Aggregations over ufunc outputs: e.g., np.sum(np.exp(...)), np.mean(np.sin(...)).
Broadcast-based summary table
Use broadcasting to compute a (3,4) array panel_totals_per_farm = total per panel (sum across hours for each panel), and then compute a (3,) boolean needs_maintenance saying True if any panel in that farm has total < 40. Use np.min, np.max, np.any, np.all.
Final KPIs (aggregation)
Compute:
overall_total (sum of all farms),
peak_hour value (max across hours) and which farm & panel produced it (use np.argmax with careful unraveling),
average_per_panel across all farms.



In [ ]:
import numpy as np

farmA = np.array([
    [10, 12, 11],
    [9, 13, 12],
    [8, 11, 10],
    [10, 10, 9]
])

farmB = np.array([
    [14, 15, 16],
    [13, 14, 15],
    [12, 13, 14],
    [15, 14, 13]
])

farmC = np.array([
    [20, 22, 21],
    [18, 19, 20],
    [17, 18, 19],
    [21, 20, 22]
])

production_all = np.stack([farmA, farmB, farmC]).astype(float)

print('Shape:', production_all.shape)
print('Size:', production_all.size)
print('Dtype:', production_all.dtype)
print('Dimensions:', production_all.ndim)

total_per_farm = production_all.sum(axis=(1,2))
mean_per_farm = production_all.mean(axis=(1,2))
std_per_farm = production_all.std(axis=(1,2))
var_per_farm = production_all.var(axis=(1,2))

print('Total per farm:', total_per_farm)
print('Mean per farm:', mean_per_farm)
print('Std per farm:', std_per_farm)
print('Var per farm:', var_per_farm)

hour_weights = np.array([0.5, 1.0, 0.75])
weighted_per_panel = np.array([np.dot(farm, hour_weights) for farm in production_all])
print('Weighted per panel shape:', weighted_per_panel.shape)

production_all[1] += 0.5

mean_per_farm_expand = mean_per_farm[:, np.newaxis, np.newaxis]
std_per_farm_expand = std_per_farm[:, np.newaxis, np.newaxis]
normalized = (production_all - mean_per_farm_expand) / std_per_farm_expand

exp_norm = np.exp(normalized)
expm1_norm = np.expm1(normalized)
log_norm = np.log(np.abs(normalized) + 1e-6)
log10_norm = np.log10(np.abs(normalized) + 1e-6)
log2_norm = np.log2(np.abs(normalized) + 1e-6)

sin_norm = np.sin(normalized)
cos_norm = np.cos(normalized)
tan_norm = np.tan(normalized)
arcsin_norm = np.arcsin(np.clip(normalized, -1, 1))
arccos_norm = np.arccos(np.clip(normalized, -1, 1))
arctan_norm = np.arctan(normalized)
degrees_norm = np.degrees(normalized)
radians_norm = np.radians(normalized)

round_norm = np.round(normalized, 2)
floor_norm = np.floor(normalized)
ceil_norm = np.ceil(normalized)
trunc_norm = np.trunc(normalized)

high_output = production_all > 20
even_hours_mask = np.arange(production_all.shape[2]) % 2 == 0
even_hours_mask_expand = even_hours_mask[np.newaxis, np.newaxis, :]

logical_and_mask = np.logical_and(high_output, even_hours_mask_expand)
logical_or_mask = np.logical_or(high_output, even_hours_mask_expand)
logical_not_mask = np.logical_not(high_output)
logical_xor_mask = np.logical_xor(high_output, even_hours_mask_expand)

greater_equal_mask = np.greater_equal(production_all, 20)
less_mask = np.less(production_all, 10)

alerts = np.array([
    [[1,0,1],[0,0,1],[1,1,0],[0,1,0]],
    [[0,1,0],[1,0,0],[1,0,1],[0,0,1]],
    [[1,1,0],[0,1,1],[1,0,1],[1,0,0]]
], dtype=int)

bit_and = np.bitwise_and(alerts, 1)
bit_or = np.bitwise_or(alerts, 0)
bit_invert = np.bitwise_not(alerts)

add_res = np.add(normalized, 2)
sub_res = np.subtract(normalized, 1)
mul_res = np.multiply(normalized, 3)
div_res = np.divide(normalized, 2)
pow_res = np.power(normalized, 2)
mod_res = np.mod(normalized, 2)

panel_totals_per_farm = production_all.sum(axis=2)
needs_maintenance = np.any(panel_totals_per_farm < 40, axis=1)

overall_total = production_all.sum()
peak_idx_flat = np.argmax(production_all)
peak_farm, peak_panel, peak_hour = np.unravel_index(peak_idx_flat, production_all.shape)
peak_value = production_all[peak_farm, peak_panel, peak_hour]
average_per_panel = production_all.mean(axis=2)

print('Panel totals per farm:\n', panel_totals_per_farm)
print('Needs maintenance per farm:', needs_maintenance)
print('Overall total energy:', overall_total)
print('Peak value:', peak_value, 'Farm:', peak_farm, 'Panel:', peak_panel, 'Hour:', peak_hour)
print('Average per panel across all farms:\n', average_per_panel)

Shape: (3, 4, 3)
Size: 36
Dtype: float64
Dimensions: 3
Total per farm: [125. 168. 237.]
Mean per farm: [10.41666667 14.         19.75      ]
Std per farm: [1.381927   1.08012345 1.53432939]
Var per farm: [1.90972222 1.16666667 2.35416667]
Weighted per panel shape: (3, 4)
Panel totals per farm:
 [[33.  34.  29.  29. ]
 [46.5 43.5 40.5 43.5]
 [63.  57.  54.  63. ]]
Needs maintenance per farm: [ True False False]
Overall total energy: 536.0
Peak value: 22.0 Farm: 2 Panel: 0 Hour: 1
Average per panel across all farms:
 [[11.         11.33333333  9.66666667  9.66666667]
 [15.5        14.5        13.5        14.5       ]
 [21.         19.         18.         21.        ]]


In [ ]:
arr=np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # Changed to a 2D array
b = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]) # Added another 2D array for stacking examples

print(np.vstack((a,b)))
print(np.hstack((a,b)))
print(np.column_stack((a,b)))
print(np.row_stack((a,b)))
print("-"*30)
print(np.hsplit(a,3))
print(np.vsplit(a,3)) # Now works on the 2D array 'a'
print(np.array_split(a,3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]
[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
------------------------------
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


/tmp/ipython-input-3645805315.py:7: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack((a,b)))


TasksArray Creation
Create a 1D array of numbers from 10 to 50.
Create a 3x3 array of random numbers between 0 and 1.
Array Attributes
Find the shape, size, and data type of the array you created in the previous task.
Basic Operations
Add 5 to every element of a 1D array.
Multiply two 2D arrays element-wise.
Indexing and Slicing
Create a 5x5 array of integers from 1 to 25. Extract:
The first row.
The last column.
A subarray of the first three rows and first two columns.
Aggregation
Create a 10-element array of random integers between 10 and 100. Find:
The maximum value.
The minimum value.
The mean and standard deviation.
Reshaping
Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
Broadcasting
Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
Filtering
Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
Matrix Multiplication
Create two 2x2 matrices and perform matrix multiplication.
Advanced Indexing
Given a 4x4 array, use fancy indexing to extract the diagonal elements.

In [ ]:
import numpy as np

# Array Creation
# Create a 1D array of numbers from 10 to 50.
arr_1d = np.arange(10, 51)
print("1D array from 10 to 50:", arr_1d)

# Create a 3x3 array of random numbers between 0 and 1.
arr_rand = np.random.rand(3, 3)
print("\n3x3 array of random numbers:\n", arr_rand)

# Array Attributes
# Find the shape, size, and data type of the array you created in the previous task.
print("\nAttributes of the random array:")
print("Shape:", arr_rand.shape)
print("Size:", arr_rand.size)
print("Data type:", arr_rand.dtype)

# Basic Operations
# Add 5 to every element of a 1D array.
arr_1d_plus_5 = arr_1d + 5
print("\n1D array with 5 added to each element:", arr_1d_plus_5)

# Multiply two 2D arrays element-wise.
arr_mult1 = np.array([[1, 2], [3, 4]])
arr_mult2 = np.array([[5, 6], [7, 8]])
arr_element_wise_mult = arr_mult1 * arr_mult2
print("\nElement-wise multiplication of two 2D arrays:\n", arr_element_wise_mult)

# Indexing and Slicing
# Create a 5x5 array of integers from 1 to 25.
arr_5x5 = np.arange(1, 26).reshape(5, 5)
print("\n5x5 array of integers from 1 to 25:\n", arr_5x5)

# Extract the first row.
first_row = arr_5x5[0, :]
print("\nFirst row of the 5x5 array:", first_row)

# Extract the last column.
last_column = arr_5x5[:, -1]
print("Last column of the 5x5 array:", last_column)

# Extract a subarray of the first three rows and first two columns.
subarray = arr_5x5[0:3, 0:2]
print("Subarray of the first three rows and first two columns:\n", subarray)

# Aggregation
# Create a 10-element array of random integers between 10 and 100.
arr_agg = np.random.randint(10, 101, 10)
print("\n10-element array of random integers:", arr_agg)

# Find the maximum value.
max_value = np.max(arr_agg)
print("Maximum value:", max_value)

# Find the minimum value.
min_value = np.min(arr_agg)
print("Minimum value:", min_value)

# Find the mean and standard deviation.
mean_value = np.mean(arr_agg)
std_dev = np.std(arr_agg)
print("Mean:", mean_value)
print("Standard deviation:", std_dev)

# Reshaping
# Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
arr_1_to_12 = np.arange(1, 13)
arr_reshaped = arr_1_to_12.reshape(3, 4)
print("\n1D array reshaped into a 3x4 matrix:\n", arr_reshaped)

# Broadcasting
# Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
arr_ones = np.ones((3, 3))
arr_to_add = np.array([1, 2, 3])
arr_broadcasted = arr_ones + arr_to_add
print("\n3x3 matrix of ones with [1, 2, 3] added to each row (broadcasting):\n", arr_broadcasted)

# Filtering
# Create a 1D array of random integers between 1 and 50.
arr_filter = np.random.randint(1, 51, 20)
print("\nOriginal array for filtering:", arr_filter)

# Extract all elements that are divisible by 5.
filtered_arr = arr_filter[arr_filter % 5 == 0]
print("Elements divisible by 5:", filtered_arr)

# Matrix Multiplication
# Create two 2x2 matrices and perform matrix multiplication.
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
matrix_mult_result = np.dot(matrix1, matrix2)
print("\nMatrix multiplication of two 2x2 matrices:\n", matrix_mult_result)

# Advanced Indexing
# Given a 4x4 array, use fancy indexing to extract the diagonal elements.
arr_4x4 = np.arange(1, 17).reshape(4, 4)
print("\nOriginal 4x4 array:\n", arr_4x4)

# Extract diagonal elements using fancy indexing
diagonal_elements = arr_4x4[[0, 1, 2, 3], [0, 1, 2, 3]]
print("Diagonal elements using fancy indexing:", diagonal_elements)

1D array from 10 to 50: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]

3x3 array of random numbers:
 [[0.34922704 0.90801228 0.93286736]
 [0.45060666 0.7712327  0.92467635]
 [0.25147641 0.42780093 0.5631367 ]]

Attributes of the random array:
Shape: (3, 3)
Size: 9
Data type: float64

1D array with 5 added to each element: [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]

Element-wise multiplication of two 2D arrays:
 [[ 5 12]
 [21 32]]

5x5 array of integers from 1 to 25:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

First row of the 5x5 array: [1 2 3 4 5]
Last column of the 5x5 array: [ 5 10 15 20 25]
Subarray of the first three rows and first two columns:
 [[ 1  2]
 [ 6  7]
 [11 12]]

10-element array of random integers: [11 54 76 75 99 18 17 83 71 12]
Maximum value: 99
Minimum value

In [ ]:
import numpy as np

# array from 10 to 50
arr=np.arange(10,51)
print(arr)
print("-"*30)
# 3x3 random matrix
arr_1=np.random.random((3,3))
print(arr_1)
print("-"*30)
print(arr_1.shape)
print(arr_1.size)
print(arr_1.dtype)
print("-"*30)
print(arr+5)
print("-"*30)
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
print(a*b)
print("-"*30)
arr_2=np.arange(1,26).reshape(5,5)
print(arr_2)
print("-"*30)
print(arr_2[0,:])
print(arr_2[:,-1])
print(arr_2[:3,:2])
print("-"*30)
arr_3=np.random.randint(10,101,size=10)
print(arr_3)
print("-"*30)
print(arr_3.max())
print(arr_3.min())
print(arr_3.mean())
print(arr_3.std())
print("-"*30)
arr_4=np.random.randint(10,101,size=12)
arr_5=arr_4.reshape(3,4)
print(arr_5)
print("-"*30)
c=[1,1,1,1]
print(arr_5+c)
print("-"*30)
arr_6=np.random.randint(1,51,20)
print(arr_6)
print(arr_6[arr_6%5==0])
print("-"*30)
d=np.array([[1,2,4],[3,5,6]])
e=np.array([[1,2],[3,4],[5,6]])
print(np.dot(d,e))
print("-"*30)
arr_7=np.arange(1,17).reshape(4,4)
print(arr_7)
print("-"*30)
ind=np.diag(arr_7)
print(ind)
print("-"*30)
index=[[1,2],[0,0],[1,1],[2,2]]
print(index)
print(arr_7[index])
print("-"*30)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
------------------------------
[[0.76724097 0.35417919 0.64736875]
 [0.35613861 0.03395552 0.70800899]
 [0.47166366 0.88137871 0.46711316]]
------------------------------
(3, 3)
9
float64
------------------------------
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
------------------------------
[[ 7 16 27]
 [40 55 72]]
------------------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
------------------------------
[1 2 3 4 5]
[ 5 10 15 20 25]
[[ 1  2]
 [ 6  7]
 [11 12]]
------------------------------
[48 99 63 28 74 61 14 23 64 39]
------------------------------
99
14
51.3
24.65785878781854
------------------------------
[[46 68 14 22]
 [88 83 45 55]
 [74 28 37 34]]
------------------------------
[[47 69 15 23]
 [89 84 46 56]
 [

In [ ]:
import numpy as np

# Create a 4x4 array
arr_4x4 = np.arange(1, 17).reshape(4, 4)
print("Original 4x4 array:\n", arr_4x4)
print("-" * 30)

# Extract diagonal elements using fancy indexing
# We need the row indices [0, 1, 2, 3] and the corresponding column indices [0, 1, 2, 3]
diagonal_elements_fancy = arr_4x4[[0, 1, 2, 3], [0, 1, 2, 3]]
print("Diagonal elements using fancy indexing:", diagonal_elements_fancy)

Original 4x4 array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
------------------------------
Diagonal elements using fancy indexing: [ 1  6 11 16]
